// @ts-check
import sitemap from '@astrojs/sitemap'
import starlight from '@astrojs/starlight'
import { defineConfig } from 'astro/config'

/**
 * The site exists to be indexed. Everything here that looks like ceremony is
 * load-bearing for that: `site` is what makes canonical URLs and the sitemap
 * absolute, and the locale table is what makes hreflang correct.
 *
 * English is the root locale, so it has no prefix: `/quickstart/` rather than
 * `/en/quickstart/`. Chinese is `/zh/`. The pairing is declared once, here, and
 * everything downstream - sitemap alternates, the language picker, the
 * canonical tag - reads it from this table rather than repeating it.
 */
export default defineConfig({
  site: 'https://douyin.wtf',
  trailingSlash: 'always',

  integrations: [
    starlight({
      title: {
        en: 'Douyin_TikTok_Download_API',
        'zh-CN': 'Douyin_TikTok_Download_API',
      },
      description:
        'A self-hosted data API for Douyin and TikTok. REST, MCP and a web console, ' +
        'with an identity pool that maintains itself. Open source and free to run.',

      // `zh-CN` rather than the more precise `zh-Hans`, and it was measured
      // rather than assumed: Starlight ships interface translations keyed by
      // `zh-CN`, and under `zh-Hans` every Chinese page rendered its navigation,
      // its search box and its "On this page" heading in English. Carrying a
      // private copy of Starlight's UI strings to win a point about writing
      // systems versus regions is the wrong trade - `zh-CN` is a valid hreflang
      // value and Google reads it as Simplified Chinese either way.
      defaultLocale: 'root',
      locales: {
        root: { label: 'English', lang: 'en' },
        zh: { label: '简体中文', lang: 'zh-CN' },
      },

      logo: {
        src: './src/assets/logo.svg',
        alt: 'Douyin_TikTok_Download_API',
      },

      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/Evil0ctal/Douyin_TikTok_Download_API',
        },
      ],

      editLink: {
        // Points at the upstream file, not at this repository. Somebody who
        // spots a mistake should land where the text actually lives.
        baseUrl:
          'https://github.com/Evil0ctal/Douyin_TikTok_Download_API/edit/main/documents/',
      },

      // Spelled out rather than autogenerated, for two reasons.
      //
      // `autogenerate: { directory: '.' }` renders an empty group: it wants a
      // real subdirectory of the content collection, and with English as the
      // root locale every page sits at the collection root instead. That was
      // live for an afternoon - a "Documentation" heading that expanded to
      // nothing.
      //
      // And seventeen pages in one flat list is not a table of contents. These
      // are the groups the upstream `documents/README.md` already sorts them
      // into, which are organised by what the reader is trying to do rather
      // than by what the file is called.
      //
      // Entries are `slug`, not `link`: Starlight then resolves each one into
      // the reader's own locale and takes the label from that page's own
      // frontmatter, so the Chinese sidebar is Chinese without a second table
      // here to keep in step.
      sidebar: [
        {
          label: 'Start here',
          translations: { 'zh-CN': '从这里开始' },
          items: [{ slug: 'quickstart' }, { slug: 'concepts' }, { slug: 'console-overview' }],
        },
        {
          label: 'Deploy it',
          translations: { 'zh-CN': '部署' },
          items: [{ slug: 'installation' }, { slug: 'configuration' }, { slug: 'security' }],
        },
        {
          label: 'Run it',
          translations: { 'zh-CN': '使用与运维' },
          items: [
            { slug: 'identities-and-proxies' },
            { slug: 'playground-and-tools' },
            { slug: 'downloads-and-library' },
            { slug: 'users-and-api-keys' },
            { slug: 'operations' },
          ],
        },
        {
          label: 'Build against it',
          translations: { 'zh-CN': '对接开发' },
          items: [{ slug: 'api' }, { slug: 'mcp' }, { slug: 'cli' }],
        },
        {
          label: 'When it breaks',
          translations: { 'zh-CN': '遇到问题' },
          items: [{ slug: 'troubleshooting' }, { slug: 'faq' }, { slug: 'contributing' }],
        },
        {
          label: 'Live demo',
          translations: { 'zh-CN': '在线演示' },
          link: 'https://demo.douyin.wtf',
          attrs: { target: '_blank', rel: 'noopener' },
          badge: { text: 'try it', variant: 'success' },
        },
      ],

      expressiveCode: {
        shiki: {
          // The installation page shows a Caddyfile, and Shiki ships no grammar
          // for one. Without this the build prints a warning per occurrence per
          // language on every deploy; the blocks render as plain text either
          // way, so the only thing the alias changes is the noise.
          langAlias: { caddyfile: 'plaintext' },
        },
      },

      customCss: ['./src/styles/custom.css'],

      head: [
        {
          tag: 'link',
          attrs: { rel: 'alternate', type: 'text/plain', href: '/llms.txt' },
        },
        // Starlight declares `twitter:card: summary_large_image` and then had
        // no image to put in it, so every share of this site rendered as a
        // blank rectangle. The card is a real screenshot of the console rather
        // than a logo: what the reader is deciding is whether to run this, and
        // the answer is easier to give with the thing on screen.
        {
          tag: 'meta',
          attrs: { property: 'og:image', content: 'https://douyin.wtf/og.png' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:width', content: '1200' },
        },
        {
          tag: 'meta',
          attrs: { property: 'og:image:height', content: '630' },
        },
        {
          tag: 'meta',
          attrs: {
            property: 'og:image:alt',
            content:
              'The Douyin_TikTok_Download_API console, showing the identity pool with live health and cooldown state',
          },
        },
        {
          tag: 'meta',
          attrs: { name: 'twitter:image', content: 'https://douyin.wtf/og.png' },
        },
      ],
    }),

    sitemap({
      i18n: {
        defaultLocale: 'en',
        locales: { en: 'en', zh: 'zh-CN' },
      },
    }),
  ],
})
