import { docsLoader } from '@astrojs/starlight/loaders'
import { docsSchema } from '@astrojs/starlight/schema'
import { defineCollection } from 'astro:content'

/**
 * `src/content/docs` is generated by `scripts/sync-docs.mjs` from the upstream
 * submodule and is git-ignored. Nothing in it is authored here except the two
 * landing pages, which live in `src/landing/` and are copied in by that script.
 */
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
}
